MOOC/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :attachments

  resources :flags

  resources :lectures do
   member do
    put "like", to: "lectures#like"
    put "flag", to: "lectures#flag"
   end
  end

  post 'comments' => 'comments#create', as: "create_comment"

  resources :lectures

  resources :courses

  get 'home/index'
  get 'home/about'

  devise_for :users
  devise_for ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'home#index'

end

MOOC/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    user ||= User.new # guest user (not logged in)
     if user.has_role? :admin
       can :manage, :all
     elsif user.has_role? :instructor
       can :manage, Course, user_id: user.id
       can :manage, Lecture, user_id: user.id
     elsif user.has_role? 'regular'
        can :like, Lecture, user_id: user_id
        can :flag, Lecture, user_id: user_id
     end





    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

MOOC/app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :lecture
end

MOOC/app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

MOOC/app/models/course.rb
class Course < ActiveRecord::Base
  resourcify
  belongs_to :user
  has_many :lectures

  validates_presence_of :title, :user_id

end

MOOC/app/models/flag.rb
class Flag < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
end

MOOC/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  acts_as_commentable
  acts_as_votable
  
  belongs_to :course
  has_many :comments
  has_many :likes
  has_many :flags

  validates_presence_of :description, :course_id
  mount_uploader :video, VideoUploader
  mount_uploaders :attachments, AttachmentUploader
  serialize :attachments, JSON
end

MOOC/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
end

MOOC/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  scope :normal_user_roles, -> {where.not(name: 'admin')}
end

MOOC/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  rolify

  has_many :courses, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :flags, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  validates_presence_of :email
  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  after_create :set_user_role
  def set_user_role
      if self.roles.empty?
        self.roles = Role.where(name: 'regular')
      end
  end
  scope :not_regular_users, -> {User.joins(:roles).where.not(roles: {name: 'regular'}).distinct}
end

MOOC/app/controllers/flags_controller.rb
class FlagsController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]
  private

    def flag_params
      params.require(:flag).permit(:lecture_id, :user_id)
    end
end

MOOC/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

MOOC/app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]

  def show
    @lecture = Lecture.find_by(id: params[:id])
    @comments = @lecture.comments
  end

  def like
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_by current_user
    redirect_to :back
  end

  def flag
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_by current_user
    redirect_to :back
  end

  private
    def lecture_params
      params.require(:lecture).permit( :description, :video, :course_id,  {attachments: []})
    end
end

MOOC/app/controllers/likes_controller.rb
class LikesController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]
  
  private

    def like_params
      params.require(:like).permit(:lecture_id, :user_id)
    end
end

MOOC/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

MOOC/app/helpers/application_helper.rb
module ApplicationHelper
end

MOOC/app/helpers/attachments_helper.rb
module AttachmentsHelper
end

MOOC/app/helpers/comments_helper.rb
module CommentsHelper
end

MOOC/app/helpers/courses_helper.rb
module CoursesHelper
end

MOOC/app/helpers/flags_helper.rb
module FlagsHelper
end

MOOC/app/helpers/home_helper.rb
module HomeHelper
end

MOOC/app/helpers/lectures_helper.rb
module LecturesHelper
end

MOOC/app/helpers/likes_helper.rb
module LikesHelper
end

MOOC/app/helpers/users_helper.rb
module UsersHelper
end

MOOC/app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.collection_select(:course_id, Course.all, :id, :title) %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.cktext_area :description %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.file_field :video %>
  </div>

  <div class="field">
    <%= f.label :attachments %><br>
    <%= f.file_field :attachments, multiple: true  %>
    <%= f.hidden_field :attachments_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MOOC/app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

MOOC/app/views/lectures/index.html.erb
<h1>Listing lectures</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Video</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead><table>
    <thead>
      <tr>
        <th>Description</th>
        <th>Video</th>
        <th>Course</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @course.lectures.each do |lecture| %>
        <tr>
          <td><%= raw(lecture.description) %></td>
          <td><%= link_to 'Video Download', lecture.video_url %></td>
          <td><%= link_to lecture.course.title, lecture.course %></td>
          <td><%= link_to 'Show', lecture %></td>
          <% if can? :edit, lecture %>
          <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
          <% end %>
          <% if can? :destroy, lecture %>
          <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= raw(lecture.description) %></td>
        <td><%= link_to 'Video Download', lecture.video_url %></td>
        <td><%= link_to lecture.course.title, lecture.course %></td>
        <td><%= link_to 'Show', lecture %></td>
        <% if can? :edit, lecture %>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <% end %>
        <% if can? :destroy, lecture %>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, @lecture %>
<%= link_to 'New Lecture', new_lecture_path %>
<% end %>

MOOC/app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

MOOC/app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">

        <!-- Blog Post -->

        <!-- Title -->
        <h1><%= link_to @lecture.course.title, @lecture.course %> > Lecture</h1>

        <!-- Author -->
        <p class="lead">
            by <%= "#{@lecture.course.user.first_name} #{@lecture.course.user.last_name}" %>
        </p>

        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @lecture.created_at.strftime("%b %d, %Y") %> at <%= @lecture.created_at.strftime("%H:%M") %></p>

        <hr>

        <!-- Preview Image -->
        <%= video_tag "#{@lecture.video_url}", :size => "700x500", :controls => true %>

        <hr>

        <!-- Post Content -->
        <p class="lead"><% raw(@lecture.description) %></p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Blog Comments -->
        <!-- Comments Form -->
        <div class="well">
            <h4>Leave a Comment:</h4>
            <%= form_tag create_comment_path, method: "post", role: 'form' do %>
              <%= hidden_field_tag "id", @lecture.id %>
              <div class="form-group">
                <%= text_area_tag :comment, nil, :class => 'form-control', :rows => 3 %>
                </div>
                <%= submit_tag "Submit" , {:class => 'btn btn-primary'}%>
              <% end %>
        </div>

        <hr>
        <!-- Posted Comments -->
        <h4>Students Feedback:</h4>
        <% @comments.each do |comment| %>
        <!-- Comment -->
        <div class="media">
            <a class="pull-left" href="#">
                <%= image_tag comment.user.avatar.thumb , :class=> 'media-object' %>
            </a>
            <div class="media-body">
                <h4 class="media-heading">by <%= "#{comment.user.first_name} #{comment.user.last_name}" %>
                    <small><%= time_ago_in_words(comment.created_at) %></small>
                </h4>
                <%= comment.comment %>
            </div>
        </div>
        <% end %>
    </div>


    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

            <!-- Blog Search Well -->
            <div class="well">
                <h4>Vote | Report</h4>
                <%= link_to like_lecture_path(@lecture), method: :put do %>
                  <span class="glyphicon glyphicon-thumbs-up"></span>
                  <%= @lecture.get_upvotes.size %>
                <% end %>
                <br>
                <%= link_to flag_lecture_path(@lecture), method: :put do %>
                  <span class="glyphicon glyphicon-thumbs-down"></span>
                  <%= @lecture.get_downvotes.size %>
                <% end %>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Attachments:</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled">
                            <% @lecture.attachments.each do |attachment| %>
                            <li>
                            > <%= link_to attachment.identifier, attachment.url, target: '_blank' %>
                            </li>
                            <% end %>

                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>

            <div class="well">
                <% if can?(:edit, @lecture) || can?(:destroy, @lecture) %>
                <div class="panel panel-primary">
                <div class="panel-heading">
                <h3 class="panel-title">Instructor Options</h3>
                </div>
                <div class="panel-body">
                <div class="btn-group">
                      <ul  class="nav nav-pills">
                  <% if can? :edit, @lecture %>
                  <li>
                  <%= link_to 'Edit', edit_lecture_path(@lecture), {:class => 'btn btn-warning'} %>
                </li>
                  <% end %>

                  <% if can? :destroy, @lecture %>
                  <li>
                  <%= link_to 'Destroy', @lecture, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                </li>
                  <% end %>
                </ul>
                </div>
                </div>
                </div>
                <% end %>
            </div>

    <!-- Blog Sidebar Widgets Column -->
    <%= render 'layouts/sidebar' %>
</div>
<!-- /.row -->