MOOC/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :attachments

  resources :flags

  resources :lectures do
   member do
    put "like", to: "lectures#like"
    put "flag", to: "lectures#flag"
   end
  end

  post 'comments' => 'comments#create', as: "create_comment"

  resources :lectures

  resources :courses

  get 'home/index'
  get 'home/about'

  devise_for :users
  devise_for ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'home#index'

end

MOOC/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    user ||= User.new # guest user (not logged in)
     if user.has_role? :admin
       can :manage, :all
     elsif user.has_role? :instructor
       can :manage, Course, user_id: user.id
       can :manage, Lecture, user_id: user.id
     elsif user.has_role? 'regular'
        can :like, Lecture, user_id: user_id
        can :flag, Lecture, user_id: user_id
     end





    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

MOOC/app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :lecture
end

MOOC/app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

MOOC/app/models/course.rb
class Course < ActiveRecord::Base
  resourcify
  belongs_to :user
  has_many :lectures

  validates_presence_of :title, :user_id

end

MOOC/app/models/flag.rb
class Flag < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
end

MOOC/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  acts_as_commentable
  acts_as_votable
  
  belongs_to :course
  has_many :comments
  has_many :likes
  has_many :flags

  validates_presence_of :description, :course_id
  mount_uploader :video, VideoUploader
  mount_uploaders :attachments, AttachmentUploader
  serialize :attachments, JSON
end

MOOC/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
end

MOOC/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  scope :normal_user_roles, -> {where.not(name: 'admin')}
end

MOOC/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  rolify

  has_many :courses, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :flags, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  validates_presence_of :email
  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  after_create :set_user_role
  def set_user_role
      if self.roles.empty?
        self.roles = Role.where(name: 'regular')
      end
  end
  scope :not_regular_users, -> {User.joins(:roles).where.not(roles: {name: 'regular'}).distinct}
end

MOOC/app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]

  def index
    @courses = Course.order("title").page(params[:page]).per(1)
  end
  private
    def course_params
      params.require(:course).permit(:title, :user_id)
    end
end

MOOC/app/controllers/flags_controller.rb
class FlagsController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]
  private

    def flag_params
      params.require(:flag).permit(:lecture_id, :user_id)
    end
end

MOOC/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

MOOC/app/controllers/likes_controller.rb
class LikesController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]
  
  private

    def like_params
      params.require(:like).permit(:lecture_id, :user_id)
    end
end

MOOC/app/helpers/application_helper.rb
module ApplicationHelper
end

MOOC/app/helpers/attachments_helper.rb
module AttachmentsHelper
end

MOOC/app/helpers/comments_helper.rb
module CommentsHelper
end

MOOC/app/helpers/courses_helper.rb
module CoursesHelper
end

MOOC/app/helpers/flags_helper.rb
module FlagsHelper
end

MOOC/app/helpers/home_helper.rb
module HomeHelper
end

MOOC/app/helpers/lectures_helper.rb
module LecturesHelper
end

MOOC/app/helpers/likes_helper.rb
module LikesHelper
end

MOOC/app/helpers/users_helper.rb
module UsersHelper
end

MOOC/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.select(:user_id, User.not_regular_users.collect {|p| [ p.email, p.id ] },{},{ :multiple => false, :size => 5 }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MOOC/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

MOOC/app/views/courses/index.html.erb
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Courses
                    <small>Listing courses</small>
                </h1>
                <ol class="breadcrumb">
                    <li>
                      <%= link_to 'Home', home_index_path %>
                    </li>
                    <li class="active">Courses</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
        <% @courses.each do |course| %>
            <!-- Blog Post Row -->
            <div class="row">
                <div class="col-md-1 text-center">
                    <p><i class="fa fa-camera fa-4x"></i>
                    </p>
                    <p><%= course.created_at.strftime("%d %b %Y") %></p>
                    <p><%= course.created_at.strftime("%H:%M") %></p>
                </div>
                <div class="col-md-5">
                    <a href="blog-post.html">
                        <img class="img-responsive img-hover" src="http://placehold.it/600x300" alt="">
                    </a>
                </div>
                <div class="col-md-6">
                    <h3>
                        <%= link_to course.title, course %>
                    </h3>
                    <p>by <%= "#{course.user.first_name} #{course.user.last_name}" %>
                    </p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <%= link_to(course) do %>
                    <span class='btn btn-primary'>Read More <i class="fa fa-angle-right"></i></span>
                    <% end %>

                </div>

            </div>
            <br>
            <% if can?(:edit, course) || can?(:destroy, course) %>
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">Instructor Options</h3>
              </div>
              <div class="panel-body">
              <div class="btn-group">
                      <ul  class="nav nav-pills">
                  <% if can? :edit, course %>
                  <li>
                  <%= link_to 'Edit', edit_course_path(course), {:class => 'btn btn-warning'} %>
                </li>
                  <% end %>

                  <% if can? :destroy, course %>
                  <li>
                  <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </li>
                  <% end %>
          </ul>
              </div>
              </div>
            </div>
            <% end %>

            <!-- /.row -->
            <hr>
            <hr>
        <% end %>
        <!-- Pager -->
        <%= paginate @courses %>
        <!-- /.row -->
<hr>
<% if can? :create, :course %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Add New Course</h3>
  </div>
  <div class="panel-body">
    <%= link_to 'New Lecture', new_lecture_path, {:class => 'btn btn-primary'} %>
    <%= link_to 'New Course', new_course_path, {:class => 'btn btn-info'} %>
    
  </div>
</div>

<% end %>

MOOC/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

MOOC/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <h1 class="page-header">
            <%= link_to @course.title, courses_path %>
            <small>By: <%= "#{@course.user.first_name} #{@course.user.last_name}" %></small>
        </h1>
<% counter=0 %>
<% @course.lectures.each do |lecture| %>
        <!-- First Blog Post -->
        <h2>
            Lecture #<%= counter+=1 %>
        </h2>
        <p class="lead">
            by <%= "#{@course.user.first_name} #{@course.user.last_name}" %>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on <%= lecture.created_at.strftime("%b %d, %Y") %> at <%= lecture.created_at.strftime("%H:%M") %></p>
        <hr>
        <img class="img-responsive" src="http://placehold.it/900x300" alt="">
        <hr>
        <p><%= raw(lecture.description) %></p>
        <%= link_to(lecture) do %>
        <span class='btn btn-primary'>Read More <i class="glyphicon glyphicon-chevron-right"></i></span>
        <% end %>
<br>
<br>
<% if can?(:edit, lecture) || can?(:destroy, lecture) %>
<div class="panel panel-primary">
<div class="panel-heading">
<h3 class="panel-title">Instructor Options</h3>
</div>
<div class="panel-body">
<div class="btn-group">
      <ul  class="nav nav-pills">
  <% if can? :edit, lecture %>
  <li>
  <%= link_to 'Edit', edit_lecture_path(lecture), {:class => 'btn btn-warning'} %>
</li>
  <% end %>

  <% if can? :destroy, lecture %>
  <li>
  <%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</li>
  <% end %>
</ul>
</div>
</div>
</div>
<% end %>

<!-- /.row -->
<hr>

        <hr>
<% end %>


    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

    <%= render 'layouts/sidebar' %>
</div>
<!-- /.row -->