MOOC/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :attachments

  resources :flags

  resources :lectures do
   member do
    put "like", to: "lectures#like"
    put "flag", to: "lectures#flag"
   end
  end

  post 'comments' => 'comments#create', as: "create_comment"

  resources :lectures

  resources :courses

  get 'home/index'
  get 'home/about'

  devise_for :users
  devise_for ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'home#index'

end

MOOC/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    user ||= User.new # guest user (not logged in)
     if user.has_role? :admin
       can :manage, :all
     elsif user.has_role? :instructor
       can :manage, Course, user_id: user.id
       can :manage, Lecture, user_id: user.id
     elsif user.has_role? 'regular'
        can :like, Lecture, user_id: user_id
        can :flag, Lecture, user_id: user_id
     end





    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

MOOC/app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :lecture
end

MOOC/app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

MOOC/app/models/course.rb
class Course < ActiveRecord::Base
  resourcify
  belongs_to :user
  has_many :lectures

  validates_presence_of :title, :user_id

end

MOOC/app/models/flag.rb
class Flag < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
end

MOOC/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  acts_as_commentable
  acts_as_votable
  
  belongs_to :course
  has_many :comments
  has_many :likes
  has_many :flags

  validates_presence_of :description, :course_id
  mount_uploader :video, VideoUploader
  mount_uploaders :attachments, AttachmentUploader
  serialize :attachments, JSON
end

MOOC/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
end

MOOC/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  scope :normal_user_roles, -> {where.not(name: 'admin')}
end

MOOC/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  rolify

  has_many :courses, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :flags, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  validates_presence_of :email
  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  after_create :set_user_role
  def set_user_role
      if self.roles.empty?
        self.roles = Role.where(name: 'regular')
      end
  end
  scope :not_regular_users, -> {User.joins(:roles).where.not(roles: {name: 'regular'}).distinct}
end

MOOC/app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]

  def index
    @courses = Course.order("title").page(params[:page]).per(1)
  end
  private
    def course_params
      params.require(:course).permit(:title, :user_id)
    end
end

MOOC/app/controllers/flags_controller.rb
class FlagsController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]
  private

    def flag_params
      params.require(:flag).permit(:lecture_id, :user_id)
    end
end

MOOC/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

MOOC/app/controllers/likes_controller.rb
class LikesController < InheritedResources::Base
  load_and_authorize_resource :only => [:edit, :new]
  
  private

    def like_params
      params.require(:like).permit(:lecture_id, :user_id)
    end
end

MOOC/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

MOOC/app/helpers/application_helper.rb
module ApplicationHelper
end

MOOC/app/helpers/attachments_helper.rb
module AttachmentsHelper
end

MOOC/app/helpers/comments_helper.rb
module CommentsHelper
end

MOOC/app/helpers/courses_helper.rb
module CoursesHelper
end

MOOC/app/helpers/flags_helper.rb
module FlagsHelper
end

MOOC/app/helpers/home_helper.rb
module HomeHelper
end

MOOC/app/helpers/lectures_helper.rb
module LecturesHelper
end

MOOC/app/helpers/likes_helper.rb
module LikesHelper
end

MOOC/app/helpers/users_helper.rb
module UsersHelper
end

MOOC/app/views/flags/_form.html.erb
<%= form_for(@flag) do |f| %>
  <% if @flag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flag.errors.count, "error") %> prohibited this flag from being saved:</h2>

      <ul>
      <% @flag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lecture_id %><br>
    <%= f.text_field :lecture_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MOOC/app/views/flags/edit.html.erb
<h1>Editing flag</h1>

<%= render 'form' %>

<%= link_to 'Show', @flag %> |
<%= link_to 'Back', flags_path %>

MOOC/app/views/flags/index.html.erb
<h1>Listing flags</h1>

<table>
  <thead>
    <tr>
      <th>Lecture</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flags.each do |flag| %>
      <tr>
        <td><%= flag.lecture %></td>
        <td><%= flag.user %></td>
        <td><%= link_to 'Show', flag %></td>
        <td><%= link_to 'Edit', edit_flag_path(flag) %></td>
        <td><%= link_to 'Destroy', flag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flag', new_flag_path %>

MOOC/app/views/flags/new.html.erb
<h1>New flag</h1>

<%= render 'form' %>

<%= link_to 'Back', flags_path %>

MOOC/app/views/flags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lecture:</strong>
  <%= @flag.lecture %>
</p>

<p>
  <strong>User:</strong>
  <%= @flag.user %>
</p>

<%= link_to 'Edit', edit_flag_path(@flag) %> |
<%= link_to 'Back', flags_path %>

MOOC/app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lecture_id %><br>
    <%= f.text_field :lecture_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MOOC/app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

MOOC/app/views/likes/index.html.erb
<h1>Listing likes</h1>

<table>
  <thead>
    <tr>
      <th>Lecture</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.lecture %></td>
        <td><%= like.user %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

MOOC/app/views/likes/new.html.erb
<h1>New like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

MOOC/app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lecture:</strong>
  <%= @like.lecture %>
</p>

<p>
  <strong>User:</strong>
  <%= @like.user %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>